# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b43cf97916d7c1c3f77ad7ac3846ca1fcd643788c4ab85de644aae27231be2cd5abe9f680e08d0be793cfef45279a6e55573c96418528012118d78be232a8669

test:
  secret_key_base: d880a74a70fee6af655dacc35c048d7cc056f537452591de01f267dd0192c317c92ce6573704f40d8932c91e31c5e81d72ad8b337dc2e28958e894e1c165f24e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
